// This file is auto-generated by scripts/generate-api-types.sh
// Run 'npm run generate:types' to regenerate this file from the OpenAPI schema

// Placeholder - types will be generated when the script is run with backend running
export type paths = Record<string, any>;
export type components = {
  schemas: Record<string, any>;
};

